[2023-06-18T09:50:47.130+0000] {processor.py:157} INFO - Started process (PID=56) to work on /opt/airflow/dags/savetodb.py
[2023-06-18T09:50:47.131+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/savetodb.py for tasks to queue
[2023-06-18T09:50:47.132+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:50:47.131+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/savetodb.py
[2023-06-18T09:51:17.241+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:51:17.239+0000] {timeout.py:68} ERROR - Process timed out, PID: 56
[2023-06-18T09:51:18.081+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:51:17.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/savetodb.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/__init__.cpython-37m-x86_64-linux-gnu.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/savetodb.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/compat.pxi", line 43, in init pyarrow.lib
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/savetodb.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.6.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.6.1/best-practices.html#reducing-dag-complexity, PID: 56
[2023-06-18T09:51:18.083+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/savetodb.py
[2023-06-18T09:51:18.416+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/savetodb.py took 31.289 seconds
[2023-06-18T09:51:49.042+0000] {processor.py:157} INFO - Started process (PID=128) to work on /opt/airflow/dags/savetodb.py
[2023-06-18T09:51:49.045+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/savetodb.py for tasks to queue
[2023-06-18T09:51:49.048+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:51:49.048+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/savetodb.py
[2023-06-18T09:52:07.226+0000] {processor.py:836} INFO - DAG(s) dict_keys(['save_to_db']) retrieved from /opt/airflow/dags/savetodb.py
[2023-06-18T09:52:07.452+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:52:07.451+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-18T09:52:07.488+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:52:07.488+0000] {dag.py:3490} INFO - Setting next_dagrun for save_to_db to 2023-06-17T00:00:00+00:00, run_after=2023-06-17T00:00:00+00:00
[2023-06-18T09:52:07.926+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/savetodb.py took 19.015 seconds
[2023-06-18T09:53:11.501+0000] {processor.py:157} INFO - Started process (PID=190) to work on /opt/airflow/dags/savetodb.py
[2023-06-18T09:53:11.720+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/savetodb.py for tasks to queue
[2023-06-18T09:53:11.724+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:53:11.723+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/savetodb.py
[2023-06-18T09:53:41.811+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:53:41.807+0000] {timeout.py:68} ERROR - Process timed out, PID: 190
[2023-06-18T09:53:42.447+0000] {logging_mixin.py:149} WARNING - Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/savetodb.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.6.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.6.1/best-practices.html#reducing-dag-complexity, PID: 190
[2023-06-18T09:53:42.688+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:53:42.448+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/savetodb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/savetodb.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: numpy.core.multiarray failed to import
[2023-06-18T09:53:42.689+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/savetodb.py
[2023-06-18T09:53:46.270+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/savetodb.py took 34.775 seconds
[2023-06-18T09:54:16.758+0000] {processor.py:157} INFO - Started process (PID=265) to work on /opt/airflow/dags/savetodb.py
[2023-06-18T09:54:16.905+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/savetodb.py for tasks to queue
[2023-06-18T09:54:16.908+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:16.907+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/savetodb.py
[2023-06-18T09:54:31.026+0000] {processor.py:836} INFO - DAG(s) dict_keys(['save_to_db']) retrieved from /opt/airflow/dags/savetodb.py
[2023-06-18T09:54:31.137+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:31.137+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-18T09:54:31.178+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:31.178+0000] {dag.py:3490} INFO - Setting next_dagrun for save_to_db to 2023-06-17T00:00:00+00:00, run_after=2023-06-17T00:00:00+00:00
[2023-06-18T09:54:31.288+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/savetodb.py took 14.535 seconds
[2023-06-18T09:55:01.935+0000] {processor.py:157} INFO - Started process (PID=334) to work on /opt/airflow/dags/savetodb.py
[2023-06-18T09:55:01.983+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/savetodb.py for tasks to queue
[2023-06-18T09:55:01.985+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:01.984+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/savetodb.py
[2023-06-18T09:55:02.588+0000] {processor.py:836} INFO - DAG(s) dict_keys(['save_to_db']) retrieved from /opt/airflow/dags/savetodb.py
[2023-06-18T09:55:02.617+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:02.617+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-18T09:55:02.653+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:02.653+0000] {dag.py:3490} INFO - Setting next_dagrun for save_to_db to 2023-06-17T00:00:00+00:00, run_after=2023-06-17T00:00:00+00:00
[2023-06-18T09:55:02.764+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/savetodb.py took 0.837 seconds
[2023-06-18T09:55:32.831+0000] {processor.py:157} INFO - Started process (PID=397) to work on /opt/airflow/dags/savetodb.py
[2023-06-18T09:55:32.833+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/savetodb.py for tasks to queue
[2023-06-18T09:55:32.834+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:32.834+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/savetodb.py
[2023-06-18T09:55:34.420+0000] {processor.py:836} INFO - DAG(s) dict_keys(['save_to_db']) retrieved from /opt/airflow/dags/savetodb.py
[2023-06-18T09:55:35.598+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:35.597+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-18T09:55:35.635+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:35.635+0000] {dag.py:3490} INFO - Setting next_dagrun for save_to_db to 2023-06-17T00:00:00+00:00, run_after=2023-06-17T00:00:00+00:00
[2023-06-18T09:55:35.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/savetodb.py took 2.946 seconds
[2023-06-18T09:56:06.461+0000] {processor.py:157} INFO - Started process (PID=470) to work on /opt/airflow/dags/savetodb.py
[2023-06-18T09:56:06.468+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/savetodb.py for tasks to queue
[2023-06-18T09:56:06.470+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:06.469+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/savetodb.py
[2023-06-18T09:56:07.088+0000] {processor.py:836} INFO - DAG(s) dict_keys(['save_to_db']) retrieved from /opt/airflow/dags/savetodb.py
[2023-06-18T09:56:07.117+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:07.117+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-18T09:56:07.151+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:07.151+0000] {dag.py:3490} INFO - Setting next_dagrun for save_to_db to 2023-06-17T00:00:00+00:00, run_after=2023-06-17T00:00:00+00:00
[2023-06-18T09:56:07.297+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/savetodb.py took 0.841 seconds
[2023-06-18T09:56:37.695+0000] {processor.py:157} INFO - Started process (PID=538) to work on /opt/airflow/dags/savetodb.py
[2023-06-18T09:56:37.751+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/savetodb.py for tasks to queue
[2023-06-18T09:56:37.753+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:37.752+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/savetodb.py
[2023-06-18T09:56:38.438+0000] {processor.py:836} INFO - DAG(s) dict_keys(['save_to_db']) retrieved from /opt/airflow/dags/savetodb.py
[2023-06-18T09:56:38.532+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:38.531+0000] {dag.py:2726} INFO - Sync 1 DAGs
