[2023-06-16T00:39:03.105+0000] {processor.py:157} INFO - Started process (PID=70) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:39:03.106+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:39:03.107+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:39:03.107+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:39:03.223+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:39:03.110+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:39:03.223+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:39:03.345+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.244 seconds
[2023-06-16T00:40:15.727+0000] {processor.py:157} INFO - Started process (PID=145) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:40:15.819+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:40:15.825+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:40:15.824+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:40:15.955+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:40:15.951+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:40:15.956+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:40:16.254+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.539 seconds
[2023-06-16T00:41:57.576+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:41:57.577+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:41:57.578+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:41:57.577+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:41:57.663+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:41:57.592+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:41:57.663+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:41:57.711+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.139 seconds
[2023-06-16T00:42:27.752+0000] {processor.py:157} INFO - Started process (PID=272) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:42:27.753+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:42:27.754+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:42:27.754+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:42:27.757+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:42:27.756+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:42:27.757+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:42:27.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.070 seconds
[2023-06-16T00:43:00.397+0000] {processor.py:157} INFO - Started process (PID=341) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:43:00.427+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:43:00.428+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:43:00.428+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:43:00.598+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:43:00.431+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:43:00.599+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:43:01.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.635 seconds
[2023-06-16T00:43:31.356+0000] {processor.py:157} INFO - Started process (PID=408) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:43:31.386+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:43:31.387+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:43:31.387+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:43:31.467+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:43:31.466+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:43:31.467+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:43:31.519+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.169 seconds
[2023-06-16T00:44:02.277+0000] {processor.py:157} INFO - Started process (PID=475) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:44:02.278+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:44:02.279+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:44:02.279+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:44:02.282+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:44:02.281+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:44:02.282+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:44:02.395+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.123 seconds
[2023-06-16T00:44:36.703+0000] {processor.py:157} INFO - Started process (PID=525) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:44:36.874+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:44:36.877+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:44:36.876+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:44:37.019+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:44:36.882+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:44:37.021+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:44:37.354+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.656 seconds
[2023-06-16T00:45:13.621+0000] {processor.py:157} INFO - Started process (PID=577) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:45:13.711+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:45:13.715+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:45:13.714+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:45:14.233+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:45:13.930+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:45:14.234+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:45:14.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.815 seconds
[2023-06-16T00:45:48.652+0000] {processor.py:157} INFO - Started process (PID=635) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:45:48.848+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:45:48.851+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:45:48.851+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:45:49.477+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:45:48.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:45:49.479+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:45:50.082+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 1.436 seconds
[2023-06-16T00:46:41.665+0000] {processor.py:157} INFO - Started process (PID=692) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:46:41.736+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:46:41.737+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:46:41.737+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:46:41.745+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:46:41.744+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:46:41.746+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:46:41.850+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.190 seconds
[2023-06-16T00:47:23.866+0000] {processor.py:157} INFO - Started process (PID=761) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:47:23.932+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:47:23.934+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:47:23.934+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:47:24.291+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:47:23.937+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:47:24.294+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:47:24.711+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.851 seconds
[2023-06-16T00:48:40.013+0000] {processor.py:157} INFO - Started process (PID=834) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:48:40.142+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:48:40.143+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:48:40.143+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:48:40.146+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:48:40.145+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:48:40.147+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:48:40.310+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.302 seconds
[2023-06-16T00:49:19.369+0000] {processor.py:157} INFO - Started process (PID=894) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:49:19.426+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:49:19.429+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:49:19.428+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:49:19.438+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:49:19.435+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:49:19.439+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:49:19.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.189 seconds
[2023-06-16T00:49:49.639+0000] {processor.py:157} INFO - Started process (PID=961) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:49:49.640+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:49:49.642+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:49:49.642+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:49:49.646+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:49:49.645+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:49:49.647+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:49:49.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.131 seconds
[2023-06-16T00:50:24.753+0000] {processor.py:157} INFO - Started process (PID=1027) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:50:24.884+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:50:24.885+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:50:24.885+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:50:25.060+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:50:24.887+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:50:25.062+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:50:25.181+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.433 seconds
[2023-06-16T00:50:59.007+0000] {processor.py:157} INFO - Started process (PID=1089) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:50:59.564+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:50:59.566+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:50:59.566+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:50:59.579+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:50:59.574+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:50:59.580+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:50:59.738+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.736 seconds
[2023-06-16T00:51:32.878+0000] {processor.py:157} INFO - Started process (PID=1153) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:51:33.104+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:51:33.106+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:51:33.106+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:51:33.522+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:51:33.185+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:51:33.523+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:51:33.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.827 seconds
[2023-06-16T00:52:21.149+0000] {processor.py:157} INFO - Started process (PID=1187) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:52:21.254+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:52:21.257+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:52:21.256+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:52:21.321+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:52:21.319+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:52:21.322+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:52:21.530+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.389 seconds
[2023-06-16T00:57:15.792+0000] {processor.py:157} INFO - Started process (PID=53) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:57:15.917+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:57:15.920+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:57:15.920+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:57:16.201+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:57:15.925+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:57:16.203+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:57:16.400+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.614 seconds
[2023-06-16T00:58:57.530+0000] {processor.py:157} INFO - Started process (PID=126) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T00:58:57.877+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T00:58:57.881+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:58:57.880+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T00:58:58.051+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:58:58.047+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T00:58:58.053+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T00:58:58.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.723 seconds
[2023-06-16T01:01:50.981+0000] {processor.py:157} INFO - Started process (PID=205) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T01:01:51.179+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T01:01:51.180+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:01:51.180+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T01:01:51.541+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:01:51.227+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T01:01:51.541+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T01:01:51.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.849 seconds
[2023-06-16T01:02:25.193+0000] {processor.py:157} INFO - Started process (PID=243) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T01:02:25.208+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T01:02:25.209+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:02:25.209+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T01:02:25.212+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:02:25.211+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T01:02:25.213+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T01:02:25.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.068 seconds
[2023-06-16T01:02:55.434+0000] {processor.py:157} INFO - Started process (PID=303) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T01:02:55.435+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T01:02:55.436+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:02:55.436+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T01:02:55.439+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:02:55.438+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T01:02:55.439+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T01:02:55.541+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.110 seconds
[2023-06-16T01:03:26.090+0000] {processor.py:157} INFO - Started process (PID=368) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T01:03:26.194+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T01:03:26.195+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:03:26.195+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T01:03:26.199+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:03:26.198+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T01:03:26.200+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T01:03:26.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.173 seconds
[2023-06-16T01:03:56.284+0000] {processor.py:157} INFO - Started process (PID=435) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T01:03:56.285+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T01:03:56.286+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:03:56.286+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T01:03:56.289+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:03:56.288+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T01:03:56.289+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T01:03:56.345+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.066 seconds
[2023-06-16T09:58:08.783+0000] {processor.py:157} INFO - Started process (PID=46) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T09:58:08.892+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T09:58:08.894+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:58:08.893+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T09:58:09.114+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:58:08.896+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T09:58:09.115+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T09:58:09.219+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.443 seconds
[2023-06-16T09:58:43.588+0000] {processor.py:157} INFO - Started process (PID=112) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T09:58:43.589+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T09:58:43.590+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:58:43.590+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T09:58:43.593+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:58:43.592+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T09:58:43.594+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T09:58:43.711+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.127 seconds
[2023-06-16T09:59:14.012+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T09:59:14.056+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T09:59:14.057+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:59:14.057+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T09:59:14.060+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:59:14.059+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T09:59:14.061+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T09:59:14.139+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.132 seconds
[2023-06-16T09:59:46.030+0000] {processor.py:157} INFO - Started process (PID=224) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T09:59:46.075+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T09:59:46.076+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:59:46.075+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T09:59:46.079+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:59:46.077+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T09:59:46.079+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T09:59:46.220+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.194 seconds
[2023-06-16T10:00:16.581+0000] {processor.py:157} INFO - Started process (PID=289) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:00:16.582+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:00:16.583+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:00:16.583+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:00:16.586+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:00:16.584+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:00:16.586+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:00:16.677+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.100 seconds
[2023-06-16T10:00:52.326+0000] {processor.py:157} INFO - Started process (PID=362) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:00:52.980+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:00:52.981+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:00:52.981+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:00:53.571+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:00:53.369+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:00:53.572+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:00:53.923+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 1.601 seconds
[2023-06-16T10:01:27.172+0000] {processor.py:157} INFO - Started process (PID=411) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:01:27.173+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:01:27.175+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:01:27.175+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:01:27.180+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:01:27.178+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:01:27.181+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:01:27.227+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.061 seconds
[2023-06-16T10:01:59.074+0000] {processor.py:157} INFO - Started process (PID=477) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:01:59.076+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:01:59.077+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:01:59.077+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:01:59.081+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:01:59.079+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:01:59.081+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:01:59.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.226 seconds
[2023-06-16T10:02:34.674+0000] {processor.py:157} INFO - Started process (PID=545) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:02:34.902+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:02:34.903+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:02:34.903+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:02:35.239+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:02:34.905+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:02:35.241+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:02:35.903+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 1.234 seconds
[2023-06-16T10:03:07.842+0000] {processor.py:157} INFO - Started process (PID=584) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:03:07.959+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:03:07.962+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:03:07.961+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:03:07.970+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:03:07.967+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:03:07.971+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:03:08.094+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.261 seconds
[2023-06-16T10:03:45.973+0000] {processor.py:157} INFO - Started process (PID=633) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:03:46.087+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:03:46.089+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:03:46.088+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:03:46.186+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:03:46.092+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:03:46.187+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:03:46.483+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.515 seconds
[2023-06-16T10:05:49.203+0000] {processor.py:157} INFO - Started process (PID=712) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:05:49.265+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:05:49.267+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:05:49.267+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:05:49.379+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:05:49.315+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:05:49.380+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:05:49.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.301 seconds
[2023-06-16T10:06:19.623+0000] {processor.py:157} INFO - Started process (PID=775) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:06:19.665+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:06:19.667+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:06:19.667+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:06:19.676+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:06:19.673+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:06:19.677+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:06:19.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.190 seconds
[2023-06-16T10:06:50.086+0000] {processor.py:157} INFO - Started process (PID=843) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:06:50.087+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:06:50.088+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:06:50.088+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:06:50.091+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:06:50.090+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:06:50.091+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:06:50.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.270 seconds
[2023-06-16T10:08:20.229+0000] {processor.py:157} INFO - Started process (PID=889) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:08:20.589+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:08:20.593+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:08:20.592+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:08:20.606+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:08:20.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:08:20.608+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:08:21.178+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.956 seconds
[2023-06-16T10:08:52.052+0000] {processor.py:157} INFO - Started process (PID=937) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:08:52.053+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:08:52.054+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:08:52.054+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:08:52.058+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:08:52.057+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:08:52.059+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:08:52.244+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.200 seconds
[2023-06-16T10:13:40.927+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:13:41.012+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:13:41.013+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:13:41.013+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:13:41.186+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:13:41.015+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:13:41.186+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:13:41.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.321 seconds
[2023-06-16T10:14:14.584+0000] {processor.py:157} INFO - Started process (PID=114) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:14:14.586+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:14:14.587+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:14:14.586+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:14:14.590+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:14:14.589+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:14:14.591+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:14:14.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.148 seconds
[2023-06-16T10:14:45.134+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:14:45.135+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:14:45.136+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:14:45.136+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:14:45.138+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:14:45.137+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:14:45.139+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:14:45.208+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.077 seconds
[2023-06-16T10:15:15.290+0000] {processor.py:157} INFO - Started process (PID=240) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:15:15.291+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:15:15.292+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:15:15.292+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:15:15.295+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:15:15.293+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:15:15.295+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:15:15.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.080 seconds
[2023-06-16T10:15:45.658+0000] {processor.py:157} INFO - Started process (PID=301) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:15:45.659+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:15:45.661+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:15:45.660+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:15:45.664+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:15:45.662+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:15:45.664+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:15:45.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.083 seconds
[2023-06-16T10:16:15.891+0000] {processor.py:157} INFO - Started process (PID=369) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:16:15.909+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:16:15.910+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:16:15.909+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:16:15.912+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:16:15.911+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:16:15.913+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:16:15.958+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.070 seconds
[2023-06-16T10:16:46.581+0000] {processor.py:157} INFO - Started process (PID=437) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:16:46.627+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:16:46.628+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:16:46.628+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:16:46.632+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:16:46.630+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:16:46.633+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:16:46.754+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.177 seconds
[2023-06-16T10:17:17.545+0000] {processor.py:157} INFO - Started process (PID=505) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:17:17.778+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:17:17.781+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:17:17.780+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:17:18.092+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:17:17.785+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:17:18.094+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:17:18.335+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.794 seconds
[2023-06-16T10:18:15.173+0000] {processor.py:157} INFO - Started process (PID=573) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:18:15.252+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:18:15.254+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:18:15.253+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:18:15.312+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:18:15.255+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:18:15.314+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:18:15.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.257 seconds
[2023-06-16T10:18:45.492+0000] {processor.py:157} INFO - Started process (PID=641) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:18:45.493+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:18:45.494+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:18:45.494+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:18:45.497+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:18:45.496+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:18:45.497+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:18:45.562+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.075 seconds
[2023-06-16T10:19:15.777+0000] {processor.py:157} INFO - Started process (PID=704) to work on /opt/airflow/dags/load_dag.py
[2023-06-16T10:19:15.805+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-16T10:19:15.806+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:19:15.806+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-16T10:19:15.809+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:19:15.808+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-16T10:19:15.809+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-16T10:19:15.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.099 seconds
